# Generated by Django 3.0.6 on 2020-05-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studprofile',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
